### ISSUE TITLE
Test CBT

### ISSUE THREAD

**Issue by olivierlambert** [xenserver/xs-cbt-samples#5]
Hi there,

We would like to test it, how we could to that? CBT features aren't existing in XS 7.2

Where could I find a "beta" version of XS?

edit: I can't find alpha/beta anymore on XenServer.org :(

**Comment by robertbreker** [comment]
Hi @olivierlambert,

Thanks for reaching out!
We currently don't run a public preview for this, but we'll shortly reach out to get you set up.

Best wishes,
Robert

**Comment by olivierlambert** [comment]
Thanks!
